[package]
name = "tasoller-ui"
version = "0.1.0"
edition = "2024"
authors = ["michioxd"]
description = "Configuration utility for TASOLLER (ORIGIN)"
repository = "https://github.com/michioxd/tas-host"
homepage = "https://github.com/michioxd/tas-host"

[package.metadata.winresource]
CompanyName = "michioxd"
FileDescription = "TASOLLER (ORIGIN) configuration utility"
InternalName = "tasoller-ui.exe"
OriginalFilename = "tasoller-ui.exe"
ProductName = "TASOLLER (ORIGIN) configuration utility"

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
toml = "=1.1.6"
serialport = { version = "4.10.1", default-features = false }
slint = { version = "=1.18.1", default-features = false, features = ["std", "backend-winit", "renderer-software", "accessibility", "compat-1-2", "unstable-winit-030", "raw-window-handle-06"] }

[target.'cfg(windows)'.dependencies]
raw-window-handle = "0.6.2"
windows-sys = { version = "=0.61.2", features = ["Win32_UI_Controls_Dialogs", "Win32_Storage_FileSystem", "Win32_System_Registry", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader"] }

[build-dependencies]
slint-build = "=1.18.1"
winresource = "0.1.31"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
incremental = false
